
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/springdata
    username: postgres
    password: Shustrik@531
    driver-class-name: org.postgresql.Driver
    pool:
     size: 10
  jpa:
    properties.hibernate:
     show_sql: true
     format_sql: true
    hibernate:
     ddl-auto: update
    hbm2ddl.auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: info
  file:
    name: org.example
    path: /

company:
  name: TechCorp
  size: 500